import { assert, assertEquals } from "@std/assert";
import { hashPassword, verifyPassword } from "./password.ts";

Deno.test("verifyPassword validates hashes generated by hashPassword", async () => {
  const password = "milanesadepollo";
  const hash = await hashPassword(password);

  assert(await verifyPassword(password, hash));
});

Deno.test("verifyPassword respects iteration count stored in hash", async () => {
  const password = "test123";
  const hash = await hashPassword(password);
  const [alg, _iterations, salt, digest] = hash.split("$");
  const tampered = `${alg}$1$${salt}$${digest}`;

  assertEquals(await verifyPassword(password, tampered), false);
});
